name: React API Kit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build & Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test against LTS versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Change cache to npm

    - name: Install dependencies
      run: npm ci # Use npm ci for clean installs from lock file

    - name: Lint code
      run: npm run lint # Use npm run

    - name: Check types
      run: npm run typecheck # Use npm run

    - name: Run tests
      run: npm test -- --coverage --ci --maxWorkers=2 # Use npm test (pass args after --)

    # Optional: Upload coverage report (same as before)
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: ./coverage/clover.xml
    #     fail_ci_if_error: true

    - name: Build packages
      run: npm run build # Use npm run